version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" # access the Prometheus UI from browser on port 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
    networks:
      - internal-network
    deploy:
      placement:
        constraints: [node.role == manager]
  # Task 3
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"   # UI accessible at http://localhost:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - internal-network
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Maps the Grafana web UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - internal-network
    deploy:
      placement:
        constraints: [node.role == manager]
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - internal-network
    deploy:
      placement:
        constraints: [node.role == manager]

  promtail:
    image: grafana/promtail:latest
    volumes:
      # This allows Promtail to read the raw log files generated by Docker
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - internal-network
    deploy:
      mode: global
  # hardware and OS metrics
  node_exporter:
    image: prom/node-exporter:latest
    networks:
      - internal-network
    deploy:
      mode: global
  # individual Docker containers meterics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - internal-network
    deploy:
      mode: global
  # Ping the Gateway to make sure it is alive
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - internal-network
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  internal-network:
    external: true
    name: myapp_internal-network
